update

diff --git a/configs/providers/aws/hadoop-2.10.1/hadoop-resourcemanager-cloudformation-template.yaml b/configs/providers/aws/hadoop-2.10.1/hadoop-resourcemanager-cloudformation-template.yaml
--- a/configs/providers/aws/hadoop-2.10.1/hadoop-resourcemanager-cloudformation-template.yaml
+++ b/configs/providers/aws/hadoop-2.10.1/hadoop-resourcemanager-cloudformation-template.yaml
@@ -1,5 +1,5 @@
 AWSTemplateFormatVersion: 2010-09-09
-Description: EC2 instance with MySQL installed in docker.
+Description: ResourceManager of hadoop-2.10.1 cluster.
 Parameters:
   Ec2KeyName:
     Description: Name of an existing EC2 KeyPair to enable SSH access to EC2 instances.
@@ -86,15 +86,22 @@ Parameters:
     Default: 30
     MinValue: 30
     MaxValue: 100
-  MysqlRootPassword:
-    Description: Root password for MySQL.
+  S3Home:
+    Description: S3 path for all needed jars and tars.
     Type: String
-    Default: admin
-    NoEcho:  true
-    MinLength: 1
-    MaxLength: 41
-    AllowedPattern: "[a-zA-Z0-9]*"
-    ConstraintDescription: Must contain only alphanumeric characters.
+    Default: s3://chenyi-ap-southeast-1
+  HadoopVersion:
+    Description: Hadoop version.
+    Type: String
+    Default: 2.10.1
+  HadoopFsS3Bucket:
+    Description: S3 bucket for hadoop-2.10.1 file system.
+    Type: String
+    Default: chenyi-ap-southeast-1
+  HadoopFsS3aEndpoint:
+    Description: S3a endpoint for hadoop-2.10.1 file system.
+    Type: String
+    Default: s3.ap-southeast-1.amazonaws.com
 Mappings:
   AWSInstanceType2Arch:
     t1.micro:
@@ -300,14 +307,16 @@ Resources:
             - Fn::ImportValue: !Join [ ":", [ "Raven", "EC2", "SecurityGroup" ] ]
       Tags:
         - Key: Name
-          Value: MySQL server
+          Value: Hadoop ResourceManager
       KeyName: !Ref Ec2KeyName
       UserData:
         Fn::Base64:
           Fn::Join:
             - ""
             - - |
-                #!/bin/bash -e
+                #!/bin/bash
+
+                set -e
 
                 HOME=/root
                 cd ${HOME}
@@ -320,13 +329,13 @@ Resources:
 
                 function warning() {
                     log="$(date '+%Y-%m-%d %H:%M:%S') - WARNING - $*"
-                    echo -e "\033[33m$*\033[0m"
+                    echo -e "\033[33m${log}\033[0m"
                     echo "${log}" >> shell.log
                 }
 
                 function error() {
                     log="$(date '+%Y-%m-%d %H:%M:%S') - ERROR - $*"
-                    echo -e "\033[31m$*\033[0m"
+                    echo -e "\033[31m${log}\033[0m"
                     echo "${log}" >> shell.log
                 }
 
@@ -345,51 +354,146 @@ Resources:
                     esac
                 }
 
-                logging info "Installing docker..."
-                if docker --version &> /dev/null; then
-                    logging info "Docker has already been installed."
+                if java -version &> /dev/null; then
+                    logging warning "Java has already been installed."
+                    exit
                 else
-                    sudo yum install -y docker
-                    logging info "Successfully installed docker."
+                    logging info "Java has not been installed."
                 fi
 
-                logging info "Starting docker service..."
-                if [[ $(systemctl is-active docker) == "active" ]]; then
-                    logging info "Docker service has already started."
+                logging info "Installing Java SE 8..."
+                JDK_PACKAGE=jdk-8u301-linux-x64.tar.gz
+                JDK_DECOMPRESS_NAME=jdk1.8.0_301
+              - Fn::Sub:
+                  - |
+                    S3_HOME=${S3Home}
+                  - S3Home: !Ref S3Home
+              - |
+                if [[ -f ${JDK_PACKAGE} ]]; then
+                    logging info "${JDK_PACKAGE} has already been downloaded."
                 else
-                    sudo systemctl start docker
-                    if [[ $(systemctl is-active docker) != "active" ]]; then
-                        logging error "Docker service failed to start."
+                    logging info "Downloading ${JDK_PACKAGE} from ${S3_HOME}/tars/${JDK_PACKAGE}..."
+                    aws s3 cp ${S3_HOME}/tars/${JDK_PACKAGE} "${HOME}"
+                    if [[ ! -f ${JDK_PACKAGE} ]]; then
+                        logging error "Failed to download ${JDK_PACKAGE}."
                         exit 1
                     fi
                 fi
 
-                # MySQL
-                if [[ $(systemctl is-active docker) == "active" ]]; then
-                    logging info "Docker service has already started."
+                JAVA_HOME=/usr/local/java/${JDK_DECOMPRESS_NAME}
+                JRE_HOME=${JAVA_HOME}/jre
+                if [[ -d ${JAVA_HOME} ]]; then
+                    logging info "${JDK_PACKAGE} has already been decompressed."
                 else
-                    logging error "Docker service has not been started, please start docker service first."
+                    logging info "Decompressing ${JDK_PACKAGE}..."
+                    mkdir -p /usr/local/java
+                    if ! tar -zxf ${JDK_PACKAGE} -C /usr/local/java; then
+                	    logging error "Failed to decompress ${JDK_PACKAGE}."
+                	    exit 1
+                    fi
+                fi
+
+                logging info "Setting up environment variables for java..."
+                cat << EOF >> "${HOME}"/.bash_profile
+
+                # Java
+                export JAVA_HOME=${JAVA_HOME}
+                export JRE_HOME=\${JAVA_HOME}/jre
+                export CLASSPATH=.:\${JAVA_HOME}/lib:\${JRE_HOME}/lib
+                export PATH=\${PATH}:\${JAVA_HOME}/bin
+                EOF
+                source "${HOME}"/.bash_profile
+
+                if java -version &> /dev/null; then
+                    logging info "Successfully installed java."
+                else
+                    logging error "Failed to install java."
                     exit 1
                 fi
+              - |
+                if hadoop version &> /dev/null; then
+                    logging warning "Hadoop already installed."
+                    exit
+                else
+                    logging info "Hadoop has not been installed."
+                fi
               - Fn::Sub:
-                  - |
-                    if [ -n "$(sudo docker ps -q -f name=mysql-${MYSQL_VERSION})" ]; then
-                        logging info "MySQL-${MYSQL_VERSION} is running."
-                    else
-                        sudo docker run -itd \
-                            --restart=always \
-                            --health-cmd='mysqladmin ping --silent' \
-                            --name mysql-${MYSQL_VERSION} \
-                            -p 3306:3306 \
-                            -e MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} \
-                            mysql:${MYSQL_VERSION}
-                        if [ -z "$(sudo docker ps -q -f name=mysql-${MYSQL_VERSION})" ]; then
-                            logging error "Failed to start MySQL-${MYSQL_VERSION}."
-                            exit 1
-                        fi
+                - |
+                  FS_S3_BUCKET=${HadoopFsS3Bucket}
+                  FS_S3A_ENDPOINT=${HadoopFsS3aEndpoint}
+
+                  HADOOP_VERSION=${HadoopVersion}
+                - HadoopVersion: !Ref HadoopVersion
+                  HadoopFsS3Bucket: !Ref HadoopFsS3Bucket
+                  HadoopFsS3aEndpoint: !Ref HadoopFsS3aEndpoint
+              - |
+                HADOOP_PACKAGE=hadoop-${HADOOP_VERSION}.tar.gz
+
+                logging info "Start installing hadoop ${HADOOP_VERSION}..."
+
+                if [[ -f ${HADOOP_PACKAGE} ]]; then
+                    logging info "${HADOOP_PACKAGE} has already been downloaded."
+                else
+                    logging info "Downloading ${HADOOP_PACKAGE} from AWS ${S3_HOME}/tars/${HADOOP_PACKAGE}..."
+                    if ! aws s3 cp ${S3_HOME}/tars/${HADOOP_PACKAGE} "${HOME}"; then
+                        logging error "Failed to download ${HADOOP_PACKAGE}."
+                        exit 1
                     fi
-                  - MYSQL_VERSION: 5.7.31
-                    MYSQL_ROOT_PASSWORD: !Ref MysqlRootPassword
+                fi
+
+                HADOOP_HOME=/usr/local/hadoop/hadoop-${HADOOP_VERSION}
+                if [[ -d ${HADOOP_HOME} ]]; then
+                    logging info "${HADOOP_PACKAGE} has already been decompressed."
+                else
+                    logging info "Decompressing ${HADOOP_PACKAGE}..."
+                    mkdir -p /usr/local/hadoop
+                    if ! tar -zxf ${HADOOP_PACKAGE} -C /usr/local/hadoop; then
+                        logging error "Failed to decompress ${HADOOP_PACKAGE}."
+                        exit 1
+                    fi
+                fi
+
+                ln -s $HADOOP_HOME/share/hadoop/tools/lib/*aws* $HADOOP_HOME/share/hadoop/common/lib/
+
+                logging info "Modifying hadoop configurations..."
+                cat << EOF > ${HADOOP_HOME}/etc/hadoop/core-site.xml
+                <?xml version="1.0" encoding="UTF-8"?>
+                <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
+                <configuration>
+                	<property>
+                    <name>fs.default.name</name>
+                    <value>s3a://${FS_S3_BUCKET}</value>
+                	</property>
+                  <property>
+                    <name>fs.s3a.endpoint</name>
+                    <value>${FS_S3A_ENDPOINT}</value>
+                  </property>
+                </configuration>
+                EOF
+
+                logging info "Setting up environment variables for hadoop..."
+                cat << EOF >> "${HOME}"/.bash_profile
+
+                # Hadoop
+                export HADOOP_HOME=${HADOOP_HOME}
+                export PATH=\${PATH}:\${HADOOP_HOME}/bin
+                EOF
+                source "${HOME}"/.bash_profile
+
+                if hadoop version &> /dev/null; then
+                    logging info "Successfully installed hadoop."
+                else
+                    logging error "Failed to install hadoop."
+                    exit 1
+                fi
+              - |
+                logging info "Starting yarn ResourceManager..."
+                if ${HADOOP_HOME}/sbin/yarn-daemon.sh start resourcemanager; then
+                    logging info "Successfully started Yarn ResourceManager."
+                else
+                    logging error "Failed to start Yarn ResourceManager."
+                    exit 1
+                fi
 Outputs:
   Ec2InstanceId:
     Description: Unique ID of EC2 instance.
@@ -407,4 +511,4 @@ Outputs:
     Description: Private IP of EC2 instance.
     Value: !GetAtt Ec2Instance.PrivateIp
     Export:
-      Name: !Join [ ":", [ "Raven", "MySQL", "Host" ] ]
+      Name: !Join [ ":", [ "Raven", "Hadoop", "ResourceManager" ] ]
diff --git a/configs/providers/aws/spark-3.1.1/spark-worker-cloudformation-template.yaml b/configs/providers/aws/spark-3.1.1/spark-worker-cloudformation-template.yaml
--- a/configs/providers/aws/spark-3.1.1/spark-worker-cloudformation-template.yaml
+++ b/configs/providers/aws/spark-3.1.1/spark-worker-cloudformation-template.yaml
@@ -1,5 +1,5 @@
 AWSTemplateFormatVersion: 2010-09-09
-Description: ResourceManager of hadoop cluster.
+Description: Master of spark-3.1.1 cluster(Standalone).
 Parameters:
   Ec2KeyName:
     Description: Name of an existing EC2 KeyPair to enable SSH access to EC2 instances.
@@ -86,6 +86,18 @@ Parameters:
     Default: 30
     MinValue: 30
     MaxValue: 100
+  S3Home:
+    Description: S3 path for all needed jars and tars.
+    Type: String
+    Default: s3://chenyi-ap-southeast-1
+  SparkVersion:
+    Description: Spark version.
+    Type: String
+    Default: 3.1.1
+  SparkWorkerName:
+    Description: Name of spark worker.
+    Type: String
+    Default: Spark Worker
 Mappings:
   AWSInstanceType2Arch:
     t1.micro:
@@ -299,15 +311,157 @@ Resources:
             - Fn::ImportValue: !Join [ ":", [ "Raven", "EC2", "SecurityGroup" ] ]
       Tags:
         - Key: Name
-          Value: Test Instance
+          Value: !Ref SparkWorkerName
       KeyName: !Ref Ec2KeyName
       UserData:
         Fn::Base64:
-          Fn::Sub:
-            - |
-              #!/bin/bash -xels
-              echo "Hello, ${Name}!" > hello.txt
-            - Name: World
+          Fn::Join:
+            - ""
+            - - |
+                #!/bin/bash
+
+                set -e
+
+                HOME=/root
+                cd ${HOME}
+
+                function info() {
+                    log="$(date '+%Y-%m-%d %H:%M:%S') - INFO - $*"
+                    echo -e "\033[32m${log}\033[0m"
+                    echo "${log}" >> shell.log
+                }
+
+                function warning() {
+                    log="$(date '+%Y-%m-%d %H:%M:%S') - WARNING - $*"
+                    echo -e "\033[33m${log}\033[0m"
+                    echo "${log}" >> shell.log
+                }
+
+                function error() {
+                    log="$(date '+%Y-%m-%d %H:%M:%S') - ERROR - $*"
+                    echo -e "\033[31m${log}\033[0m"
+                    echo "${log}" >> shell.log
+                }
+
+                function logging() {
+                    level=$1
+                    shift
+                    case $level in
+                    "info")
+                        info "$*";;
+                    "warning")
+                        warning "$*";;
+                    "error")
+                        error "$*";;
+                    *)
+                        echo "$*";;
+                    esac
+                }
+
+                if java -version &> /dev/null; then
+                    logging warning "Java has already been installed."
+                    exit
+                else
+                    logging info "Java has not been installed."
+                fi
+
+                logging info "Installing Java SE 8..."
+                JDK_PACKAGE=jdk-8u301-linux-x64.tar.gz
+                JDK_DECOMPRESS_NAME=jdk1.8.0_301
+              - Fn::Sub:
+                  - |
+                    S3_HOME=${S3Home}
+                  - S3Home: !Ref S3Home
+              - |
+                if [[ -f ${JDK_PACKAGE} ]]; then
+                    logging info "${JDK_PACKAGE} has already been downloaded."
+                else
+                    logging info "Downloading ${JDK_PACKAGE} from ${S3_HOME}/tars/${JDK_PACKAGE}..."
+                    aws s3 cp ${S3_HOME}/tars/${JDK_PACKAGE} "${HOME}"
+                    if [[ ! -f ${JDK_PACKAGE} ]]; then
+                        logging error "Failed to download ${JDK_PACKAGE}."
+                        exit 1
+                    fi
+                fi
+
+                JAVA_HOME=/usr/local/java/${JDK_DECOMPRESS_NAME}
+                JRE_HOME=${JAVA_HOME}/jre
+                if [[ -d ${JAVA_HOME} ]]; then
+                    logging info "${JDK_PACKAGE} has already been decompressed."
+                else
+                    logging info "Decompressing ${JDK_PACKAGE}..."
+                    mkdir -p /usr/local/java
+                    if ! tar -zxf ${JDK_PACKAGE} -C /usr/local/java; then
+                	    logging error "Failed to decompress ${JDK_PACKAGE}."
+                	    exit 1
+                    fi
+                fi
+
+                logging info "Setting up environment variables for java..."
+                cat << EOF >> "${HOME}"/.bash_profile
+
+                # Java
+                export JAVA_HOME=${JAVA_HOME}
+                export JRE_HOME=\${JAVA_HOME}/jre
+                export CLASSPATH=.:\${JAVA_HOME}/lib:\${JRE_HOME}/lib
+                export PATH=\${PATH}:\${JAVA_HOME}/bin
+                EOF
+                source "${HOME}"/.bash_profile
+
+                if java -version &> /dev/null; then
+                    logging info "Successfully installed java."
+                else
+                    logging error "Failed to install java."
+                    exit 1
+                fi
+              - |
+                SPARK_VERSION=3.1.1
+                SPARK_PACKAGE=spark-3.1.1-bin-hadoop3.2.tgz
+                SPARK_HOME=/usr/local/spark/spark-3.1.1-bin-hadoop3.2
+
+                if [[ -f ${SPARK_PACKAGE} ]]; then
+                    logging info "${SPARK_PACKAGE} has already been downloaded."
+                else
+                    logging info "Downloading ${SPARK_PACKAGE} from ${S3_HOME}/tars/${SPARK_PACKAGE}..."
+                    aws s3 cp ${S3_HOME}/tars/${SPARK_PACKAGE} "${HOME}"
+                    if [[ ! -f ${SPARK_PACKAGE} ]]; then
+                        logging error "Failed to download ${SPARK_PACKAGE}."
+                        exit 1
+                    fi
+                fi
+
+                logging info "Setting up environment variables for spark..."
+                cat << EOF >> "${HOME}"/.bash_profile
+
+                # Spark
+                export SPARK_HOME=${SPARK_HOME}
+                export PATH=\${PATH}:\${SPARK_HOME}/bin
+                EOF
+                source "${HOME}"/.bash_profile
+
+                if [[ -d ${SPARK_HOME} ]]; then
+                    logging info "${JDK_PACKAGE} has already been decompressed."
+                else
+                    logging info "Decompressing ${SPARK_PACKAGE}..."
+                    mkdir -p /usr/local/spark
+                    if ! tar -zxf ${SPARK_PACKAGE} -C /usr/local/spark; then
+                	    logging error "Failed to decompress ${SPARK_PACKAGE}."
+                	    exit 1
+                    fi
+                fi
+              - Fn::Sub:
+                  - |
+                    SPARK_MASTER=${SparkMaster}
+                  - SparkMaster:
+                      Fn::ImportValue: !Join [ ":", [ "Raven", "Spark", "Master" ] ]
+              - |
+                logging info "Starting spark worker..."
+                if ${SPARK_HOME}/sbin/start-worker.sh ${SPARK_MASTER}:7077; then
+                    logging info "Successfully started spark worker."
+                else
+                    logging error "Failed to start spark worker."
+                    exit 1
+                fi
 Outputs:
   Ec2InstanceId:
     Description: Unique ID of EC2 instance.
@@ -324,5 +478,3 @@ Outputs:
   Ec2InstancePrivateIp:
     Description: Private IP of EC2 instance.
     Value: !GetAtt Ec2Instance.PrivateIp
-    Export:
-      Name: !Join [ """:", [ "Raven", "Hadoop", "ResourceManager" ] ]
