update

diff --git a/configs/providers/aws/kylin-4.0.0/kylin-master-cloudformation-template.yaml b/configs/providers/aws/kylin-4.0.0/kylin-master-cloudformation-template.yaml
--- a/configs/providers/aws/kylin-4.0.0/kylin-master-cloudformation-template.yaml
+++ b/configs/providers/aws/kylin-4.0.0/kylin-master-cloudformation-template.yaml
@@ -1,5 +1,5 @@
 AWSTemplateFormatVersion: 2010-09-09
-Description: EC2 instance with MySQL installed in docker.
+Description: Master of kylin4.0.0 cluster.
 Parameters:
   Ec2KeyName:
     Description: Name of an existing EC2 KeyPair to enable SSH access to EC2 instances.
@@ -8,7 +8,7 @@ Parameters:
   InstanceType:
     Type: String
     Description: EC2 instance type.
-    Default: t2.small
+    Default: m5.large
     AllowedValues:
       - t1.micro
       - t2.nano
@@ -70,9 +70,6 @@ Parameters:
       - hs1.8xlarge
       - cr1.8xlarge
       - cc2.8xlarge
-  Ec2InstanceName:
-    Type: String
-    Default: Hive Metastore
   Ec2VolumeType:
     Type: String
     Default: gp2
@@ -86,17 +83,23 @@ Parameters:
       - standard
   Ec2VolumeSize:
     Type: Number
-    Default: 120
+    Default: 30
     MinValue: 30
-    MaxValue: 120
+    MaxValue: 100
   S3Home:
     Description: S3 path for all needed jars and tars.
     Type: String
     Default: s3://chenyi-ap-southeast-1
+  AwsRegion:
+    Description: AWS region.
+    Type: String
+    Default: ap-southeast-1
   HadoopVersion:
     Description: Hadoop version.
     Type: String
     Default: 3.2.0
+    AllowedValues:
+      - 3.2.0
   HadoopFsS3Bucket:
     Description: S3 bucket for hadoop-2.10.1 file system.
     Type: String
@@ -109,15 +112,16 @@ Parameters:
     Description: Hive version.
     Type: String
     Default: 2.3.9
-  MysqlRootPassword:
-    Description: Root password for MySQL.
+  SparkVersion:
+    Description: Spark version.
     Type: String
-    Default: admin
-    NoEcho:  true
-    MinLength: 1
-    MaxLength: 41
-    AllowedPattern: "[a-zA-Z0-9]*"
-    ConstraintDescription: Must contain only alphanumeric characters.
+    Default: 3.1.1
+  KylinVersion:
+    Description: Kylin version.
+    Type: String
+    Default: 4.0.0
+    AllowedValues:
+      - 4.0.0
 Mappings:
   AWSInstanceType2Arch:
     t1.micro:
@@ -323,7 +327,7 @@ Resources:
             - Fn::ImportValue: !Join [ ":", [ "Raven", "EC2", "SecurityGroup" ] ]
       Tags:
         - Key: Name
-          Value: !Ref Ec2InstanceName
+          Value: Kylin Master
       KeyName: !Ref Ec2KeyName
       UserData:
         Fn::Base64:
@@ -331,19 +335,15 @@ Resources:
             - ""
             - - |
                 #!/bin/bash
-
                 if [ ! ${USER} ]; then
                     USER=ec2-user
                 fi
-
                 if [ ! ${GROUP} ]; then
                     GROUP=ec2-user
                 fi
-
                 if [ ! ${HOME} ]; then
                     HOME=/home/${USER}
                 fi
-
                 cd ${HOME}
                 touch shell.log && chown -R ${USER}:${GROUP} shell.log
 
@@ -437,14 +437,12 @@ Resources:
                     exit 1
                 fi
 
+                logging info "Modifying the java.security file"
+                # this function is remove the unsupport tls rules in java which version of 1.8.291 and above
+                cp -f $JAVA_HOME/jre/lib/security/java.security $JAVA_HOME/jre/lib/security/java.security.bak
+                sed -e "s/\ TLSv1,\ TLSv1.1,//g" -i $JAVA_HOME/jre/lib/security/java.security
+
                 chown -R ${USER}:${GROUP} ${HOME}/java
-              - |
-                if hadoop version &> /dev/null; then
-                    logging warning "Hadoop already installed."
-                    exit
-                else
-                    logging info "Hadoop has not been installed."
-                fi
               - Fn::Sub:
                 - |
                   FS_S3_BUCKET=${HadoopFsS3Bucket}
@@ -481,16 +479,15 @@ Resources:
                     fi
                 fi
 
-                ln -s ${HADOOP_HOME}/share/hadoop/tools/lib/*aws* ${HADOOP_HOME}/share/hadoop/common/lib/
-
-                sudo chown -R ${USER}:${GROUP} ${HOME}/hadoop
+                cp ${HADOOP_HOME}/share/hadoop/tools/lib/*aws* ${HADOOP_HOME}/share/hadoop/common/lib/
 
                 logging info "Setting up environment variables for hadoop..."
                 cat << EOF >> ${HOME}/.bash_profile
 
                 # Hadoop
                 export HADOOP_HOME=${HADOOP_HOME}
-                export PATH=${PATH}:\${HADOOP_HOME}/bin:\${HADOOP_HOME}/sbin
+                export HADOOP_CONF_DIR=\${HADOOP_HOME}/etc/hadoop
+                export PATH=\${PATH}:\${HADOOP_HOME}/bin:\${HADOOP_HOME}/sbin
                 EOF
                 source ${HOME}/.bash_profile
 
@@ -516,26 +513,25 @@ Resources:
                   </property>
                 </configuration>
                 EOF
-              - |
-                logging info "Installing MariaDB..."
-                yum install -y mariadb mariadb-server
-                systemctl enable mariadb
-                systemctl start mariadb
-                aws s3 cp ${S3_HOME}/bak/hive-metastore.bak.sql ${HOME}/
+
+                chown -R ${USER}:${GROUP} ${HOME}/hadoop
               - Fn::Sub:
                 - |
                   HIVE_VERSION=${HiveVersion}
+
                   MYSQL_HOST=${MysqlHost}
                   MYSQL_USER=${MysqlUser}
                   MYSQL_PASSWORD=${MysqlPassword}
                 - HiveVersion: !Ref HiveVersion
-                  MysqlHost: localhost
+                  MysqlHost:
+                    Fn::ImportValue: !Join [ ":", [ "Raven", "Hive", "Metastore", "Host" ] ]
                   MysqlUser: hive
                   MysqlPassword: hive
               - |
                 HIVE_PACKAGE=apache-hive-${HIVE_VERSION}-bin.tar.gz
                 HIVE_DECOMPRESS_NAME=apache-hive-${HIVE_VERSION}-bin
                 HIVE_HOME=${HOME}/hive/${HIVE_DECOMPRESS_NAME}
+                AWS_SDK_VERSION=1.12.129
 
                 MYSQL_CONNECTOR_PACKAGE=mysql-connector-java-5.1.40.jar
 
@@ -597,6 +593,28 @@ Resources:
                     exit 1
                 fi
 
+                logging info "Inorder to access AWS S3, downloading needed jars from ${S3_HOME}/jars..."
+
+                if [ ! -f ${HIVE_HOME}/lib/aws-java-sdk-core-${AWS_SDK_VERSION}.jar ]; then
+                    aws s3 cp ${S3_HOME}/jars/aws-java-sdk-core-${AWS_SDK_VERSION}.jar ${HIVE_HOME}/lib
+                fi
+
+                if [ ! -f ${HIVE_HOME}/lib/aws-java-sdk-s3-${AWS_SDK_VERSION}.jar ]; then
+                    aws s3 cp ${S3_HOME}/jars/aws-java-sdk-s3-${AWS_SDK_VERSION}.jar ${HIVE_HOME}/lib
+                fi
+
+                if [ ! -f ${HIVE_HOME}/lib/hadoop-aws-${HADOOP_VERSION}.jar ]; then
+                    aws s3 cp ${S3_HOME}/jars/hadoop-aws-${HADOOP_VERSION}.jar ${HIVE_HOME}/lib
+                fi
+
+                cp ${HIVE_HOME}/conf/hive-env.sh.template ${HIVE_HOME}/conf/hive-env.sh
+
+                if [ -z "$(sed -n -e '/^export HIVE_AUX_JARS_PATH/p' ${HIVE_HOME}/conf/hive-env.sh)" ]; then
+                    cat << EOF >> ${HIVE_HOME}/conf/hive-env.sh
+                export HIVE_AUX_JARS_PATH=${HIVE_HOME}/lib/aws-java-sdk-core-${AWS_SDK_VERSION}.jar:${HIVE_HOME}/lib/aws-java-sdk-s3-${AWS_SDK_VERSION}.jar:${HIVE_HOME}/lib/hadoop-aws-${HADOOP_VERSION}.jar
+                EOF
+                fi
+
                 logging info "Modifying hive configurations..."
                 cat << EOF > ${HIVE_HOME}/conf/hive-site.xml
                 <?xml version="1.0" encoding="UTF-8" standalone="no"?>
@@ -642,12 +660,118 @@ Resources:
                 EOF
 
                 chown -R ${USER}:${GROUP} ${HOME}/hive
-                mkdir -p ${HIVE_HOME}/logs
-                nohup hive --service metastore &> ${HIVE_HOME}/logs/metastore.log &
-                nohup hive --service hiveserver2 &> ${HIVE_HOME}/logs/hiveserver2.log &
+              - Fn::Sub:
+                  - |
+                    SPARK_VERSION=${SparkVersion}
+                  - SparkVersion: !Ref SparkVersion
               - |
-                aws s3 cp ${S3_HOME}/bak/hive-metastore.bak.sql ${HOME}
-                aws s3 cp ${S3_HOME}/bak/mysql.bak.sql ${HOME}
+                SPARK_PACKAGE=spark-${SPARK_VERSION}-bin-hadoop3.2.tgz
+                SPARK_HOME=${HOME}/spark/spark-${SPARK_VERSION}-bin-hadoop3.2
+
+                mkdir -p ${HOME}/spark && cd ${HOME}/spark
+
+                if [[ -f ${SPARK_PACKAGE} ]]; then
+                    logging info "${SPARK_PACKAGE} has already been downloaded."
+                else
+                    logging info "Downloading ${SPARK_PACKAGE} from ${S3_HOME}/tars/${SPARK_PACKAGE}..."
+                    aws s3 cp ${S3_HOME}/tars/${SPARK_PACKAGE} .
+                    if [[ ! -f ${SPARK_PACKAGE} ]]; then
+                        logging error "Failed to download ${SPARK_PACKAGE}."
+                        exit 1
+                    fi
+                fi
+
+                if [[ -d ${SPARK_HOME} ]]; then
+                    logging info "${JDK_PACKAGE} has already been decompressed."
+                else
+                    logging info "Decompressing ${SPARK_PACKAGE}..."
+                    if ! tar -zxf ${SPARK_PACKAGE}; then
+                	    logging error "Failed to decompress ${SPARK_PACKAGE}."
+                	    exit 1
+                    fi
+                fi
+
+                logging info "Setting up environment variables for spark..."
+                cat << EOF >> "${HOME}"/.bash_profile
+
+                # Spark
+                export SPARK_HOME=${SPARK_HOME}
+                export PATH=\${PATH}:\${SPARK_HOME}/bin
+                EOF
+                source "${HOME}"/.bash_profile
+
+                logging info "Removing conflicting jars from hive..."
+                rm -f ${HIVE_HOME}/lib/spark-*
+                rm -f ${HIVE_HOME}/lib/jackson-module-scala_2.11-2.6.5.jar
+
+                logging info "Coping needed jars into spark from hadoop and hive"
+                if [[ ! -f ${SPARK_HOME}/jars/hadoop-aws-${HADOOP_VERSION}.jar ]]; then
+                  cp ${HADOOP_HOME}/share/hadoop/tools/lib/hadoop-aws-${HADOOP_VERSION}.jar ${SPARK_HOME}/jars/
+                fi
+
+                if [[ ! -f ${SPARK_HOME}/jars/aws-java-sdk-bundle-1.11.375.jar ]]; then
+                  cp ${HADOOP_HOME}/share/hadoop/tools/lib/aws-java-sdk-bundle-1.11.375.jar ${SPARK_HOME}/jars/
+                fi
+
+                if [[ ! -f ${SPARK_HOME}/jars/${MYSQL_CONNECTOR_PACKAGE} ]]; then
+                  cp $HIVE_HOME/lib/${MYSQL_CONNECTOR_PACKAGE} ${SPARK_HOME}/jars/
+                fi
+
+                if [[ ! -f ${SPARK_HOME}/conf/hive-site.xml ]]; then
+                  cp ${HIVE_HOME}/conf/hive-site.xml ${SPARK_HOME}/conf/
+                fi
+
+                LOCAL_IP=$(ifconfig -a | grep inet | grep -v 127.0.0.1 | grep -v inet6 | awk '{print $2}' | tr -d "addr:")
+
+                logging info "Modifying spark configurations..."
+                cat << EOF > ${SPARK_HOME}/conf/spark-defaults.conf
+                #
+                # Licensed to the Apache Software Foundation (ASF) under one or more
+                # contributor license agreements.  See the NOTICE file distributed with
+                # this work for additional information regarding copyright ownership.
+                # The ASF licenses this file to You under the Apache License, Version 2.0
+                # (the "License"); you may not use this file except in compliance with
+                # the License.  You may obtain a copy of the License at
+                #
+                #    http://www.apache.org/licenses/LICENSE-2.0
+                #
+                # Unless required by applicable law or agreed to in writing, software
+                # distributed under the License is distributed on an "AS IS" BASIS,
+                # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+                # See the License for the specific language governing permissions and
+                # limitations under the License.
+                #
+
+                # Default system properties included when running spark-submit.
+                # This is useful for setting default environmental settings.
+
+                spark.master                     spark://${LOCAL_IP}:7077
+                spark.serializer                 org.apache.spark.serializer.KryoSerializer
+                spark.driver.memory              5g
+                EOF
+
+                logging info "Starting spark master..."
+
+                if su ${USER} -c "${SPARK_HOME}/sbin/start-master.sh -h ${LOCAL_IP}"; then
+                    logging info "Successfully started spark master."
+                else
+                    logging error "Failed to start spark master."
+                    exit 1
+                fi
+
+                chown -R ${USER}:${GROUP} ${HOME}/spark
+              - |
+                # Zookeeper
+                mkdir -p ${HOME}/scripts
+                aws s3 cp ${S3_HOME}/scripts/install-zookeeper-3.4.14.sh ${HOME}/scripts/
+                su - ec2-user -c "bash ${HOME}/install-zookeeper-3.4.14.sh"
+              - |
+                # Kylin
+                aws s3 cp ${S3_HOME}/scripts/install-kylin-4.0.0-master.sh ${HOME}/scripts/
+                su - ec2-user -c "bash ${HOME}/install-kylin-4.0.0-master.sh"
+              - |
+                # Yum
+                yum install -y gcc make git
 Outputs:
   Ec2InstanceId:
     Description: Unique ID of EC2 instance.
@@ -661,17 +785,31 @@ Outputs:
   Ec2InstancePublicDnsName:
     Description: The public DNS name of the specified instance.
     Value: !GetAtt Ec2Instance.PublicDnsName
-  Ec2InstancePrivateIp:
-    Description: Private IP of EC2 instance.
+  SparkMasterPrivateIp:
+    Description: Private IP of spark master.
     Value: !GetAtt Ec2Instance.PrivateIp
-    Export:
-      Name: !Join [ ":", [ "Raven", "Hive", "Metastore", "Host" ] ]
-  HiveMetaStoreUri:
-    Description: URI of hive metastore.
+  SparkMasterUrl:
+    Description: URL of spark master.
     Value: !Join
       - ""
-      - - "thrift://"
+      - - "spark:"
         - !GetAtt Ec2Instance.PrivateIp
-        - ":9083"
-    Export:
-      Name: !Join [ ":", [ "Raven", "Hive", "Metastore", "URI" ] ]
+        - ":7077"
+  SparkWebUi:
+    Description: Web UI of spark.
+    Value: !Join
+      - ""
+      - - "http:"
+        - !GetAtt Ec2Instance.PublicIp
+        - ":8080"
+  Kylin4MasterPrivateIp:
+    Description: Private IP of kylin4 master.
+    Value: !GetAtt Ec2Instance.PrivateIp
+  Kylin4WebUi:
+    Description: Web UI of kylin4.
+    Value: !Join
+      - ""
+      - - "http:"
+        - !GetAtt Ec2Instance.PublicIp
+        - ":7070"
+        - "/kylin"
diff --git a/configs/providers/aws/kylin-4.0.0/kylin-worker-cloudformation-template.yaml b/configs/providers/aws/kylin-4.0.0/kylin-worker-cloudformation-template.yaml
--- a/configs/providers/aws/kylin-4.0.0/kylin-worker-cloudformation-template.yaml
+++ b/configs/providers/aws/kylin-4.0.0/kylin-worker-cloudformation-template.yaml
@@ -1,5 +1,5 @@
 AWSTemplateFormatVersion: 2010-09-09
-Description: EC2 instance with MySQL installed in docker.
+Description: Worker of kylin4.0.0 cluster.
 Parameters:
   Ec2KeyName:
     Description: Name of an existing EC2 KeyPair to enable SSH access to EC2 instances.
@@ -70,9 +70,6 @@ Parameters:
       - hs1.8xlarge
       - cr1.8xlarge
       - cc2.8xlarge
-  Ec2InstanceName:
-    Type: String
-    Default: Hive Metastore
   Ec2VolumeType:
     Type: String
     Default: gp2
@@ -86,9 +83,9 @@ Parameters:
       - standard
   Ec2VolumeSize:
     Type: Number
-    Default: 120
+    Default: 30
     MinValue: 30
-    MaxValue: 120
+    MaxValue: 100
   S3Home:
     Description: S3 path for all needed jars and tars.
     Type: String
@@ -97,6 +94,8 @@ Parameters:
     Description: Hadoop version.
     Type: String
     Default: 3.2.0
+    AllowedValues:
+      - 3.2.0
   HadoopFsS3Bucket:
     Description: S3 bucket for hadoop-2.10.1 file system.
     Type: String
@@ -109,15 +108,23 @@ Parameters:
     Description: Hive version.
     Type: String
     Default: 2.3.9
-  MysqlRootPassword:
-    Description: Root password for MySQL.
+  SparkVersion:
+    Description: Spark version.
     Type: String
-    Default: admin
-    NoEcho:  true
-    MinLength: 1
-    MaxLength: 41
-    AllowedPattern: "[a-zA-Z0-9]*"
-    ConstraintDescription: Must contain only alphanumeric characters.
+    Default: 3.1.1
+  SparkMasterPrivateIp:
+    Description: Private IP of spark master.
+    Type: String
+  KylinVersion:
+    Description: Kylin version.
+    Type: String
+    Default: 4.0.0
+    AllowedValues:
+      - 4.0.0
+  KylinWorkerName:
+    Description: Name of spark worker.
+    Type: String
+    Default: Kylin Worker
 Mappings:
   AWSInstanceType2Arch:
     t1.micro:
@@ -323,7 +330,7 @@ Resources:
             - Fn::ImportValue: !Join [ ":", [ "Raven", "EC2", "SecurityGroup" ] ]
       Tags:
         - Key: Name
-          Value: !Ref Ec2InstanceName
+          Value: !Ref KylinWorkerName
       KeyName: !Ref Ec2KeyName
       UserData:
         Fn::Base64:
@@ -414,8 +421,8 @@ Resources:
                 else
                     logging info "Decompressing ${JDK_TARBALL}..."
                     if ! tar -zxf ${JDK_TARBALL}; then
-                	    logging error "Failed to decompress ${JDK_TARBALL}."
-                	    exit 1
+                      logging error "Failed to decompress ${JDK_TARBALL}."
+                      exit 1
                     fi
                 fi
 
@@ -506,36 +513,33 @@ Resources:
                 <?xml version="1.0" encoding="UTF-8"?>
                 <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
                 <configuration>
-                	<property>
+                  <property>
                     <name>fs.default.name</name>
                     <value>s3a://${FS_S3_BUCKET}</value>
-                	</property>
+                  </property>
                   <property>
                     <name>fs.s3a.endpoint</name>
                     <value>${FS_S3A_ENDPOINT}</value>
                   </property>
                 </configuration>
                 EOF
-              - |
-                logging info "Installing MariaDB..."
-                yum install -y mariadb mariadb-server
-                systemctl enable mariadb
-                systemctl start mariadb
-                aws s3 cp ${S3_HOME}/bak/hive-metastore.bak.sql ${HOME}/
               - Fn::Sub:
                 - |
                   HIVE_VERSION=${HiveVersion}
+
                   MYSQL_HOST=${MysqlHost}
                   MYSQL_USER=${MysqlUser}
                   MYSQL_PASSWORD=${MysqlPassword}
                 - HiveVersion: !Ref HiveVersion
-                  MysqlHost: localhost
+                  MysqlHost:
+                    Fn::ImportValue: !Join [ ":", [ "Raven", "Hive", "Metastore", "Host" ] ]
                   MysqlUser: hive
                   MysqlPassword: hive
               - |
                 HIVE_PACKAGE=apache-hive-${HIVE_VERSION}-bin.tar.gz
                 HIVE_DECOMPRESS_NAME=apache-hive-${HIVE_VERSION}-bin
                 HIVE_HOME=${HOME}/hive/${HIVE_DECOMPRESS_NAME}
+                AWS_SDK_VERSION=1.12.129
 
                 MYSQL_CONNECTOR_PACKAGE=mysql-connector-java-5.1.40.jar
 
@@ -562,8 +566,8 @@ Resources:
                     logging info "${HIVE_PACKAGE} has already been decompressed."
                 else
                     if ! tar -zxf ${HIVE_PACKAGE}; then
-                	    logging error "Failed to decompress ${HIVE_PACKAGE}"
-                	    exit 1
+                      logging error "Failed to decompress ${HIVE_PACKAGE}"
+                      exit 1
                    fi
                 fi
 
@@ -595,6 +599,28 @@ Resources:
                 else
                     logging error "Failed to install hive."
                     exit 1
+                fi
+
+                logging info "Inorder to access AWS S3, downloading needed jars from ${S3_HOME}/jars..."
+
+                if [ ! -f ${HIVE_HOME}/lib/aws-java-sdk-core-${AWS_SDK_VERSION}.jar ]; then
+                    aws s3 cp ${S3_HOME}/jars/aws-java-sdk-core-${AWS_SDK_VERSION}.jar ${HIVE_HOME}/lib
+                fi
+
+                if [ ! -f ${HIVE_HOME}/lib/aws-java-sdk-s3-${AWS_SDK_VERSION}.jar ]; then
+                    aws s3 cp ${S3_HOME}/jars/aws-java-sdk-s3-${AWS_SDK_VERSION}.jar ${HIVE_HOME}/lib
+                fi
+
+                if [ ! -f ${HIVE_HOME}/lib/hadoop-aws-${HADOOP_VERSION}.jar ]; then
+                    aws s3 cp ${S3_HOME}/jars/hadoop-aws-${HADOOP_VERSION}.jar ${HIVE_HOME}/lib
+                fi
+
+                cp ${HIVE_HOME}/conf/hive-env.sh.template ${HIVE_HOME}/conf/hive-env.sh
+
+                if [ -z "$(sed -n -e '/^export HIVE_AUX_JARS_PATH/p' ${HIVE_HOME}/conf/hive-env.sh)" ]; then
+                    cat << EOF >> ${HIVE_HOME}/conf/hive-env.sh
+                export HIVE_AUX_JARS_PATH=${HIVE_HOME}/lib/aws-java-sdk-core-${AWS_SDK_VERSION}.jar:${HIVE_HOME}/lib/aws-java-sdk-s3-${AWS_SDK_VERSION}.jar:${HIVE_HOME}/lib/hadoop-aws-${HADOOP_VERSION}.jar
+                EOF
                 fi
 
                 logging info "Modifying hive configurations..."
@@ -642,12 +668,127 @@ Resources:
                 EOF
 
                 chown -R ${USER}:${GROUP} ${HOME}/hive
-                mkdir -p ${HIVE_HOME}/logs
-                nohup hive --service metastore &> ${HIVE_HOME}/logs/metastore.log &
-                nohup hive --service hiveserver2 &> ${HIVE_HOME}/logs/hiveserver2.log &
+              - Fn::Sub:
+                - |
+                    SPARK_VERSION=${SparkVersion}
+                - SparkVersion: !Ref SparkVersion
               - |
-                aws s3 cp ${S3_HOME}/bak/hive-metastore.bak.sql ${HOME}
-                aws s3 cp ${S3_HOME}/bak/mysql.bak.sql ${HOME}
+                SPARK_PACKAGE=spark-${SPARK_VERSION}-bin-hadoop3.2.tgz
+                SPARK_HOME=${HOME}/spark/spark-${SPARK_VERSION}-bin-hadoop3.2
+
+                mkdir -p ${HOME}/spark && cd ${HOME}/spark
+
+                if [[ -f ${SPARK_PACKAGE} ]]; then
+                    logging info "${SPARK_PACKAGE} has already been downloaded."
+                else
+                    logging info "Downloading ${SPARK_PACKAGE} from ${S3_HOME}/tars/${SPARK_PACKAGE}..."
+                    aws s3 cp ${S3_HOME}/tars/${SPARK_PACKAGE} .
+                    if [[ ! -f ${SPARK_PACKAGE} ]]; then
+                        logging error "Failed to download ${SPARK_PACKAGE}."
+                        exit 1
+                    fi
+                fi
+
+                if [[ -d ${SPARK_HOME} ]]; then
+                    logging info "${JDK_PACKAGE} has already been decompressed."
+                else
+                    logging info "Decompressing ${SPARK_PACKAGE}..."
+                    if ! tar -zxf ${SPARK_PACKAGE}; then
+                      logging error "Failed to decompress ${SPARK_PACKAGE}."
+                      exit 1
+                    fi
+                fi
+
+                logging info "Setting up environment variables for spark..."
+                cat << EOF >> "${HOME}"/.bash_profile
+
+                # Spark
+                export SPARK_HOME=${SPARK_HOME}
+                export PATH=\${PATH}:\${SPARK_HOME}/bin
+                EOF
+                source "${HOME}"/.bash_profile
+
+                logging info "Removing conflicting jars from hive..."
+                rm -f ${HIVE_HOME}/lib/spark-*
+                rm -f ${HIVE_HOME}/lib/jackson-module-scala_2.11-2.6.5.jar
+
+                logging info "Coping needed jars into spark from hadoop and hive"
+                if [[ ! -f ${SPARK_HOME}/jars/hadoop-aws-${HADOOP_VERSION}.jar ]]; then
+                  cp ${HADOOP_HOME}/share/hadoop/tools/lib/hadoop-aws-${HADOOP_VERSION}.jar ${SPARK_HOME}/jars/
+                fi
+
+                if [[ ! -f ${SPARK_HOME}/jars/aws-java-sdk-bundle-1.11.375.jar ]]; then
+                  cp ${HADOOP_HOME}/share/hadoop/tools/lib/aws-java-sdk-bundle-1.11.375.jar ${SPARK_HOME}/jars/
+                fi
+
+                if [[ ! -f ${SPARK_HOME}/jars/${MYSQL_CONNECTOR_PACKAGE} ]]; then
+                  cp $HIVE_HOME/lib/${MYSQL_CONNECTOR_PACKAGE} ${SPARK_HOME}/jars/
+                fi
+
+                if [[ ! -f ${SPARK_HOME}/conf/hive-site.xml ]]; then
+                  cp ${HIVE_HOME}/conf/hive-site.xml ${SPARK_HOME}/conf/
+                fi
+              - Fn::Sub:
+                - |
+                  SPARK_MASTER=${SparkMasterPrivateIp}
+                - SparkMasterPrivateIp: !Ref SparkMasterPrivateIp
+              - |
+                logging info "Starting spark worker..."
+                if su ${USER} -c "nohup ${SPARK_HOME}/sbin/start-worker.sh ${SPARK_MASTER}:7077"; then
+                    logging info "Successfully started spark worker."
+                else
+                    logging error "Failed to start spark worker."
+                    exit 1
+                fi
+
+                chown -R ${USER}:${GROUP} ${HOME}/spark
+              - Fn::Sub:
+                  - |
+                    KYLIN_VERSION=${KylinVersion}
+                  - KylinVersion: !Ref KylinVersion
+              - |
+                KYLIN_PACKAGE=apache-kylin-${KYLIN_VERSION}-bin-spark3.tar.gz
+                KYLIN_HOME=${HOME}/kylin/apache-kylin-${KYLIN_VERSION}-bin-spark3
+
+                logging info "Installing kylin4.0.0..."
+                mkdir -p ${HOME}/kylin && cd ${HOME}/kylin
+
+                if [ -f ${KYLIN_PACKAGE} ]; then
+                    logging info "${KYLIN_PACKAGE} has already been downloaded."
+                else
+                    logging info "Downloading ${KYLIN_PACKAGE} from ${S3_HOME}/tars/${KYLIN_PACKAGE}..."
+                    aws s3 cp ${S3_HOME}/tars/${KYLIN_PACKAGE} .
+                    if [ ! -f ${KYLIN_PACKAGE} ]; then
+                        logging error "Failed to download ${KYLIN_PACKAGE}."
+                        exit 1
+                    fi
+                fi
+
+                if [ -d ${KYLIN_HOME} ]; then
+                    logging info "${KYLIN_PACKAGE} has already been decompressed."
+                else
+                    logging info "Decompressing ${KYLIN_PACKAGE}..."
+                    if ! tar -zxf ${KYLIN_PACKAGE}; then
+                        logging error "Failed to decompress ${KYLIN_PACKAGE}."
+                        exit 1
+                    fi
+                fi
+
+                if [ -n "$(sed -n -e '/KYLIN_HOME/p' ${HOME}/.bash_profile)" ]; then
+                    logging info "Kylin environment variables have already been set."
+                else
+                    logging info "Setting up environment variables for kylin..."
+                    cat << EOF >> ${HOME}/.bash_profile
+
+                # Kylin
+                export KYLIN_HOME=${KYLIN_HOME}
+                EOF
+                fi
+
+                source ${HOME}/.bash_profile
+
+                chown -R ${USER}:${GROUP} ${HOME}/kylin
+
 Outputs:
   Ec2InstanceId:
     Description: Unique ID of EC2 instance.
@@ -664,14 +805,3 @@ Outputs:
   Ec2InstancePrivateIp:
     Description: Private IP of EC2 instance.
     Value: !GetAtt Ec2Instance.PrivateIp
-    Export:
-      Name: !Join [ ":", [ "Raven", "Hive", "Metastore", "Host" ] ]
-  HiveMetaStoreUri:
-    Description: URI of hive metastore.
-    Value: !Join
-      - ""
-      - - "thrift://"
-        - !GetAtt Ec2Instance.PrivateIp
-        - ":9083"
-    Export:
-      Name: !Join [ ":", [ "Raven", "Hive", "Metastore", "URI" ] ]
